features:
  httpGateway: 
    feature: http-gateway
  webMonitor:
    feature: web-monitor
  usernamePasswordAuthentication:
    feature: authentication
    settings: 
      driver: usernamePassword
  

directories:
  ..:
    nestDepth: 2